# Generated by Django 5.1.2 on 2024-10-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_produto_querido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='querido',
            new_name='querinha_galera',
        ),
    ]
