# Generated by Django 5.1.2 on 2024-10-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_rename_querido_produto_querinha_galera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='querinha_galera',
            new_name='queridinho_da_galera',
        ),
    ]
