# Generated by Django 5.1.2 on 2024-10-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_rename_querinha_galera_produto_queridinho_da_galera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='preco_total',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='qtd_comprada',
        ),
    ]
