# Generated by Django 5.1.2 on 2024-10-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_remove_compra_preco_total_remove_compra_qtd_comprada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moeda',
            name='qtd_moeda',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
