# Generated by Django 5.1.2 on 2024-10-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_produto_imagem_alter_moeda_qtd_moeda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
