# Generated by Django 5.1.2 on 2024-10-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(default='', max_length=100),
        ),
    ]
